name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'type:enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type:bug'
  - title: '🧰 Maintenance'
    labels:
      - 'type:chore'
      - 'type:refactor'
version-template": "$MAJOR.$MINOR.$PATCH"
version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'type:enhancement'
      - 'semver:minor'
  patch:
    labels:
      - 'type:bug'
      - 'type:chore'
      - 'type:refactor'
  default: patch
template: |
  ## Changes
  $CHANGES